# Generated by Django 5.0.6 on 2024-06-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrbanWard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mpererwe', 'Mpererwe'), ('Kasangati', 'Kasangati'), ('Gayaza', 'Gayaza'), ('Wamewo', 'Wamewo')], max_length=50)),
            ],
        ),
    ]
