# Generated by Django 5.0.6 on 2024-06-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufarm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urbanward',
            name='name',
            field=models.CharField(choices=[('Mpererwe', 'Mpererwe'), ('Kasangati', 'Kasangati'), ('Gayaza', 'Gayaza'), ('Wampewo', 'Wampewo')], max_length=50),
        ),
    ]
