# Generated by Django 5.0.6 on 2024-06-15 14:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufarm_app', '0002_alter_urbanward_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ufarm_app.urbanward')),
            ],
        ),
    ]
