# Generated by Django 5.0.6 on 2024-06-15 14:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufarm_app', '0003_farmerone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmerone',
            options={'verbose_name_plural': 'farmer one'},
        ),
        migrations.AlterModelOptions(
            name='urbanward',
            options={'verbose_name_plural': 'urban ward'},
        ),
        migrations.CreateModel(
            name='UrbanFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('farmer_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ufarm_app.farmerone')),
            ],
        ),
    ]
