# Generated by Django 5.0.6 on 2024-06-15 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufarm_app', '0004_alter_farmerone_options_alter_urbanward_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerone',
            name='activities',
            field=models.TextField(default=True, max_length=200, validators=[django.core.validators.MinLengthValidator(20)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerone',
            name='address',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerone',
            name='contact',
            field=models.CharField(default=True, max_length=15, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerone',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=True, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerone',
            name='nin',
            field=models.CharField(default=True, max_length=13, validators=[django.core.validators.MinLengthValidator(13)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerone',
            name='period_of_stay',
            field=models.CharField(choices=[('5yrs', '5yrs'), ('6yrs', '6yrs'), ('7yrs', '7yrs'), ('8yrs', '8yrs'), ('9yrs', '9yrs'), ('10+ yrs', '10+ yrs')], default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerone',
            name='residence',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Owner', 'Owner')], default=True, max_length=6),
            preserve_default=False,
        ),
    ]
