# Generated by Django 5.0.6 on 2024-06-15 21:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufarm_app', '0005_farmerone_activities_farmerone_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urbanfarmer',
            name='farmer_one',
        ),
        migrations.AddField(
            model_name='urbanfarmer',
            name='activities',
            field=models.TextField(default=True, max_length=200, validators=[django.core.validators.MinLengthValidator(20)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urbanfarmer',
            name='address',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urbanfarmer',
            name='contact',
            field=models.CharField(default=True, max_length=15, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urbanfarmer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=True, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urbanfarmer',
            name='nin',
            field=models.CharField(default=True, max_length=13, validators=[django.core.validators.MinLengthValidator(13)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urbanfarmer',
            name='unique_id',
            field=models.CharField(default=True, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urbanfarmer',
            name='ward',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='ufarm_app.urbanward'),
            preserve_default=False,
        ),
    ]
