# Generated by Django 5.0.6 on 2024-06-15 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufarm_app', '0006_remove_urbanfarmer_farmer_one_urbanfarmer_activities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('unit_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('mode_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money')], max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('mode_of_delivery', models.CharField(choices=[('Pick up', 'Pick up'), ('Home Delivery', 'Home Delivery')], max_length=40)),
                ('produce_type', models.CharField(choices=[('Organic', 'Organic'), ('None Organic', 'None Organic')], max_length=20)),
                ('ward_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ufarm_app.urbanward')),
            ],
        ),
    ]
